AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-demo

  Playground for trying out AWS SAM features

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ADTConvertFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ADT-convert/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        ADTConvert:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /convert
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ADTConvertApi:
    Description: "API Gateway endpoint for Prod stage for ADT Convert function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/convert/"
  ADTConvertFunction:
    Description: "ADT Converter Lambda Function ARN"
    Value: !GetAtt ADTConvertFunction.Arn
  ADTConvertFunctionIamRole:
    Description: "Implicit IAM Role created for ADT Convert function"
    Value: !GetAtt ADTConvertFunctionRole.Arn
